version: '3'
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
    networks:
      - kafka_network

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    restart: always
    ports:
      - 3000:3000
    environment:
      - NEXTAUTH_SECRET=asdflakisdflkiasdlkfias
    networks:
      - kafka_network

networks:
  kafka_network:
    name: kafka_docker_example_net
    driver: bridge
   